### ISSUE TITLE
Sandbox password for cloudera vm does not work

### ISSUE THREAD

**Issue by jomach** [KyloIO/kylo-docs#16]
the password provided on the documentation does not work. 

what is the root password for the kylo-cloudera-sandbox-0.8.3.ova ?

**Comment by jeremymerrifield** [comment]
The password is "kylo"

**Comment by jomach** [comment]
solve : https://github.com/KyloIO/kylo-docs/pull/17

**Comment by freastro** [comment]
This is fixed in the docs now. Thanks!
